apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metabase-operator
  template:
    metadata:
      labels:
        name: metabase-operator
    spec:
      serviceAccountName: metabase-operator
      containers:
        - name: metabase-operator
          # Replace this with the built image name
          image: gcr.io/codelity-co/metabase-operator:v0.2.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "metabase-operator"
